<?xml version="1.0" encoding="ISO-8859-1"?>
<!--Profiler generated XSL-File-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:template match="/">
		<html>
			<head><title>Profiler</title></head>
			<body>
				<font face="verdana,helvetia,arial">
					<div class="logosubtext"> Information: <font color="blue"><strong><xsl:value-of select="*/@TITLE"/></strong></font></div>
					<div class="logosubtext">Generated by: <font color="blue"><strong><xsl:value-of select="*/@AUTHOR"/></strong></font></div>
					<div class="logosubtext">Date of profiling:
						<font color="blue">
							<strong>
								<xsl:value-of select="Profiler/Data/Header/Time/Hour"/>:
								<xsl:value-of select="Profiler/Data/Header/Time/Minute"/>:
								<xsl:value-of select="Profiler/Data/Header/Time/Second"/> - 
								<xsl:value-of select="Profiler/Data/Header/Time/Day"/>.
								<xsl:value-of select="Profiler/Data/Header/Time/Month"/>.
								<xsl:value-of select="Profiler/Data/Header/Time/Year"/>
							</strong>
						</font>
					</div>
					<hr/>
					<div style="border:1px solid black; padding:.5em; font-size:smaller">
						<a><xsl:attribute name="NAME">TOC</xsl:attribute>Table of contents:</a>
						<xsl:for-each select="*/Definition|*/Data/Header|*/Data/ProfiledObj|*/Data/LoggingNotDisplayed|*/Interpretation">
							<div style="margin-left:1em">
								<a><xsl:attribute name="HREF">#<xsl:value-of select="@CONTENT"/></xsl:attribute><xsl:value-of select="@CONTENT"/></a>
							</div>
						</xsl:for-each>
					</div>
					<hr/>
					<xsl:for-each select="*/Definition|*/Data/Header|*/Data/ProfiledObj|*/Data/LoggingNotDisplayed|*/Interpretation">
						<dl>
							<dt>
								<span style="font-size:smaller">
									<a><xsl:attribute name="NAME"><xsl:value-of select="@CONTENT"/></xsl:attribute><b><xsl:value-of select="@CONTENT"/></b></a>
									<br/>
									<a><xsl:attribute name="HREF">#TOC</xsl:attribute><span style="color:red; font-size: smallest">Back to contents</span></a>
								</span>
							</dt>
							<dd><xsl:apply-templates select="LogMode|BufferSize|AddDataSize|LogEvent|ObjectCnt|DataCnt|TicksPerUsec|Library|Objects|Entries|Calculation"/></dd>
						</dl>
					</xsl:for-each>
					<hr/>
				</font>
			</body>
		</html>
	</xsl:template>
	<xsl:template match="LogMode">
		<font face="arial" color="blue" size="2"><strong>Loggingmode: </strong></font><xsl:value-of select="node()"/><br/>
	</xsl:template>
	<xsl:template match="BufferSize">
		<font face="arial" color="blue" size="2"><strong>Size of the Logging buffer: </strong></font><xsl:value-of select="node()"/><br/>
	</xsl:template>
	<xsl:template match="AddDataSize">
		<font face="arial" color="blue" size="2"><strong>Size of the Additional data: </strong></font><xsl:value-of select="node()"/><br/>
	</xsl:template>
	<xsl:template match="LogEvent ">
		<font face="arial" color="blue" size="2"><strong>Logged events: </strong></font>
		<table border="0" width="60%" style="margin-left:1em">
			<tr><td width="100%"/></tr>
			<xsl:for-each select="EventType"><xsl:sort order="ascending" case-order="lower-first" select="node()"/><xsl:value-of select="node()"/><br/></xsl:for-each>
		</table>
	</xsl:template>
	<xsl:template match="ObjectCnt">
		<font face="arial" color="blue" size="2"><strong>Number of System- and task objects: </strong></font><xsl:value-of select="node()"/><br/>
	</xsl:template>
	<xsl:template match="DataCnt">
		<font face="arial" color="blue" size="2"><strong>Number of Logging entries: </strong></font><xsl:value-of select="node()"/><br/>
	</xsl:template>
	<xsl:template match="TicksPerUsec">
		<font face="arial" color="blue" size="2"><strong>Number of Ticks per µs: </strong></font><xsl:value-of select="node()"/><br/>
	</xsl:template>
	<xsl:template match="Library">
		<font face="arial" color="blue" size="2"><strong>Logged libraries: </strong></font>
		<table border="0" width="60%" style="margin-left:1em">
			<tr><td width="100%"/></tr>
			<xsl:for-each select="LibFunction"><xsl:sort order="ascending" case-order="lower-first" select="node()"/><xsl:value-of select="node()"/><br/></xsl:for-each>
		</table>
	</xsl:template>
	<xsl:template match="Objects">
		<table border="1">
			<tr>
				<td width="auto" bgcolor="yellow">Module</td>
				<td width="auto" bgcolor="yellow">Priority</td>
				<td width="auto" bgcolor="yellow">Stack Size [Byte]</td>
				<td width="auto" bgcolor="yellow">Free Stack [Byte]</td>
				<td width="auto" bgcolor="yellow">Supervisor Stack Size [Byte]</td>
				<td width="auto" bgcolor="yellow">Free Supervisor Stack [Byte]</td>
			</tr>
			<tr>
				<xsl:for-each select="ProfObject">
					<xsl:sort case-order="lower-first" order="ascending"  select="ObjectName"/>
					<tr>
						<td><xsl:value-of select="ObjectName"/></td>
						<td><xsl:value-of select="ObjectPriority"/></td>
						<td><xsl:value-of select="StackSize"/></td>
						<td><xsl:value-of select="StackFree"/></td>
						<td><xsl:value-of select="StackSizeSV"/></td>
						<td><xsl:value-of select="StackFreeSV"/></td>
					</tr>
				</xsl:for-each>
			</tr>
		</table>
	</xsl:template>
	<!--xsl:template match="Entries">
		<table border="1">
			<tr>
				<td width="auto" bgcolor="yellow">Object Name</td>
				<td width="auto" bgcolor="yellow">Time Stamp [µs]</td>
				<td width="auto" bgcolor="yellow">Event ID</td>
				<td width="auto" bgcolor="yellow">Additional Data</td>
			</tr>
			<tr>
				<xsl:for-each select="LogEntry">
					<tr>
						<td><xsl:value-of select="@ObjectName"/></td>
						<td><xsl:value-of select="TimeStamp"/></td>
						<td><xsl:value-of select="EventId"/></td>
						<td><xsl:value-of select="AdditionalData"/></td>
					</tr>
				</xsl:for-each>
			</tr>
		</table>
	</xsl:template -->
	<xsl:template match="Calculation">
		<table border="1">
			<tr>
				<td width="auto" bgcolor="yellow">Module</td>
				<td width="auto" bgcolor="yellow">Object Type</td>
				<td width="auto" bgcolor="yellow">Call count</td>
				<td width="auto" bgcolor="yellow">min. Net Time [µs]</td>
				<td width="auto" bgcolor="yellow">avg. Net Time [µs]</td>
				<td width="auto" bgcolor="yellow">max. Net Time [µs]</td>
				<td width="auto" bgcolor="yellow">min. Gross Time [µs]</td>
				<td width="auto" bgcolor="yellow">avg. Gross Time [µs]</td>
				<td width="auto" bgcolor="yellow">max. Gross Time [µs]</td>
				<td width="auto" bgcolor="yellow">CPU Usage [%]</td>
			</tr>
			<tr>
				<xsl:for-each select="Result">
					<xsl:sort order="ascending" case-order="lower-first" select="ObjectName"/>
					<tr>
						<td><xsl:value-of select="ObjectName"/></td>
						<td><xsl:value-of select="ObjectType"/></td>
						<td><xsl:value-of select="CallCnt"/></td>
						<td><xsl:value-of select="NettoMinTime"/></td>
						<td><xsl:value-of select="NettoAverageTime"/></td>
						<td><xsl:value-of select="NettoMaxTime"/></td>
						<td><xsl:value-of select="BruttoMinTime"/></td>
						<td><xsl:value-of select="BruttoAverageTime"/></td>
						<td><xsl:value-of select="BruttoMaxTime"/></td>
						<td><xsl:value-of select="CpuUsage"/></td>
					</tr>
				</xsl:for-each>
			</tr>
		</table>
	</xsl:template>
</xsl:stylesheet>
